version: 2

release:
  prerelease: auto

builds:
  - main: .
    binary: hello-cli
    ldflags:
      - -s -w
      - -X github.com/ludleth/hello-cli/cmd.Version={{ .Tag }}
      - -X github.com/ludleth/hello-cli/cmd.Commit={{ .ShortCommit }}
      - -X github.com/ludleth/hello-cli/cmd.BuildTime={{ .Date }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "hello-cli_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
